# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muyPicky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
