# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muyPicky', '0003_auto_20170822_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlocation',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
